version: "3.8"
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis

  # Database Postgres
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  # Django Application
  app:
    build: .
    volumes:
      - .:/docker
    env_file: "./docker/env"
    ports:
      - 8000:8000
    image: app:docker
    container_name: docker_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
      
  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l DEBUG
    volumes:
      - .:/docker
    env_file: "./docker/env"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    container_name: celery
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: