# Generated by Django 3.2.14 on 2022-08-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_commentnews_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
